#!groovy
node {
    final def jsClientDir = 'javascript'

    stage('Checkout') {
        git url: "https://github.com/eclipse/ditto-clients.git", branch: "master"
    }

    dir(jsClientDir) {
        stage('Install dependencies') {
            sh 'npm install'
        }
        stage('Lint') {
            sh 'npm run lint'
        }
        stage('Build') {
            sh 'npm run build'
        }
        stage('Test') {
            sh 'npm run test'
            // TODO: there will no be test reports as of now
            junit allowEmptyResults: false, testResults: 'target/test-report.xml'
        }
        // TODO: rename the param
        if (params.deploy) {
            stage('Publish release') {
                sh 'npm run release:publish'
            }
        }
    }

}
